#!/usr/bin/expect -f
spawn git pull origin master

#Expect interacts with git authentication
#It waits for "ass" text (that matches "Password", "password", "passphrase") and then it sends your password.
expect "Username"
send "sagban_\r"

expect
send "IMSAGARb#9975\r"
interact
