#!/usr/bin/expect -f
spawn service nginx restart

#Expect interacts with git authentication
#It waits for "ass" text (that matches "Password", "password", "passphrase") and then it sends your password.
expect "ass"
send "studentportal123\r"
interact