#!/usr/bin/expect -f
spawn sudo service gunicorn restart

set password [lindex $argv 0];

#Expect interacts with git authentication
#It waits for "ass" text (that matches "Password", "password", "passphrase") and then it sends your password.
expect "ass"
send "$password\r"
interact
